import { formatMoney } from './international';
import type { TermsRegion } from './legal-market';

export type TermsSection = { id: string; title: string; paragraphs: string[]; link?: { href: string; label: string } };
export function termsContent(region: TermsRegion, language: 'da' | 'en', prices: {standard: number; custom: number | null; currency?: string}): TermsSection[] {
  const danish = region === 'eu' && language === 'da';
  const choose = (da: string, en: string) => danish ? da : en;
  const monthly = formatMoney(prices.standard, prices.currency??'DKK', danish ? 'da' : 'en');
  const setup = prices.custom == null ? choose('den engangspris, der vises før bestilling', 'the one-time price disclosed before ordering') : formatMoney(prices.custom, prices.currency??'DKK', danish ? 'da' : 'en');
  const section = (id: string, daTitle: string, enTitle: string, pairs: [string, string][]): TermsSection => ({ id, title: choose(daTitle, enTitle), paragraphs: pairs.map(([da,en]) => choose(da,en)) });
  const sections: TermsSection[] = [
    section('platform', 'Platformen og din aftalepart', 'The platform and your contracting party', [
      ['RacketBuddy er en platform for klubdrift, banebooking, trænere og medspillere. Aftalen om at bruge selve platformen indgås med RacketBuddy LLC. Selskabets adresse og kontaktoplysninger står øverst i dette dokument.', 'RacketBuddy is a platform for club operations, court bookings, coaches and playing partners. Your agreement to use the platform is with RacketBuddy LLC. Its address and contact details appear at the top of this document.'],
      ['Når du køber banetid, træning, medlemskab eller klubkredit, er den klub eller træner, der fremgår af tilbuddet, leverandør af ydelsen. Leverandøren har ansvar for faciliteter, træning, sikkerhed, beskrivelser og sine egne lovpligtige oplysninger. RacketBuddy formidler aftalen og håndterer de betalings- og administrationsfunktioner, der er tilsluttet.', 'When you purchase court time, coaching, a membership or club credit, the club or coach identified in the offer supplies that service. The provider is responsible for facilities, coaching, safety, descriptions and its legally required disclosures. RacketBuddy facilitates the agreement and operates the connected payment and administration functions.'],
      ['En klub køber sit RacketBuddy-abonnement og sin Custom-løsning direkte hos RacketBuddy LLC. Et medlemskab af en klub er en anden aftale end klubbens abonnement på platformen.', 'A club purchases its RacketBuddy subscription and Custom solution directly from RacketBuddy LLC. A player’s club membership is a separate agreement from the club’s platform subscription.'],
    ]),
    section('account', 'Konto, alder og ansvar', 'Accounts, age and authority', [
      ['Du skal være mindst 18 år for at oprette konto og indgå købsaftaler. En forælder eller værge kan booke på vegne af en mindreårig. En klubadministrator skal være bemyndiget til at indgå aftaler for klubben og administrere de oplysninger, vedkommende tilføjer.', 'You must be at least 18 to create an account and enter purchase agreements. A parent or guardian may book for a minor. Club administrators must have authority to enter agreements for the club and administer the information they add.'],
      ['Angiv korrekte oplysninger, beskyt dit login, og kontakt os ved mistanke om misbrug. Du må ikke give uvedkommende adgang til medlemsoplysninger, betalingsoplysninger eller klubbens adgangsstyring.', 'Provide accurate information, protect your login and contact us if you suspect misuse. Do not give unauthorised people access to member data, payment information or facility access controls.'],
    ]),
    section('price-payment', 'Priser, valuta og betaling', 'Prices, currency and payment', [
      ['Nye klubabonnementer afregnes i EUR i Europa, inklusive Danmark, og USD i USA og Canada. De annoncerede klubpriser er ekskl. eventuel moms eller sales tax. Det samlede beløb beregnes i checkout før betaling. Eksisterende aftaler og kvitteringer beholder deres aftalte valuta.', 'New club subscriptions are billed in EUR in Europe, including Denmark, and USD in the US and Canada. Advertised club prices exclude applicable VAT or sales tax. The total is calculated at checkout before payment. Existing contracts and receipts retain their agreed currency.'],
      ['Pris, valuta, leverandør, indhold og eventuelle skatter eller gebyrer skal fremgå før køb. Baner og træning kan prissættes i klubbens eller trænerens valuta. Dit sprogvalg omregner ikke prisen. Din bank kan opkræve egne valuta- eller kortgebyrer.', 'The price, currency, provider, service and any taxes or fees must be disclosed before purchase. Courts and coaching can be priced in the provider’s currency. Changing the interface language does not convert the price. Your bank may charge its own currency-conversion or card fees.'],
      ['En bookingbetaling opkræves, når betalingen gennemføres; det er ikke en garanti for, at beløbet kun reserveres på kortet. De tilgængelige betalingsmetoder vises på betalingssiden. Kortdata håndteres af betalingsudbyderen. En gratis booking eller booking betalt med klubkredit kan bekræftes uden kortbetaling.', 'A booking payment is collected when payment completes; it is not a promise that funds will only be authorised on your card. Available payment methods are shown at checkout. Card details are handled by the payment provider. A free booking or a booking covered by club credit can be confirmed without a card payment.'],
      ['Klubber og trænere skal færdiggøre betalingsudbyderens identitets- og bankopsætning for at modtage relevante onlinebetalinger. Betalingsudbyderens egne vilkår, gebyrer og krav gælder sideløbende. Der tilføjes ikke et skjult RacketBuddy-annulleringsgebyr til spillerens refundering.', 'Clubs and coaches must complete the payment provider’s identity and banking setup to receive the relevant online payments. The provider’s own terms, fees and requirements also apply. RacketBuddy does not add a hidden cancellation fee to a player’s refund.'],
    ]),
    section('bookings', 'Bookinger og bekræftelse', 'Bookings and confirmation', [
      ['En midlertidig reservation er ikke en bekræftet booking. Tiden kan holdes, mens du betaler, indtil den viste betalingsfrist. Når en betalingssag er startet, kan fristen være længere end den oprindelige reservation. Ved manglende betaling frigives tiden efter reservationens og betalingsforsøgets afslutning.', 'A temporary hold is not a confirmed booking. A slot may be held while you pay until the displayed checkout deadline. Starting a payment attempt can extend the initial hold. An unpaid slot is released after the reservation and payment attempt have ended.'],
      ['Bookingen er bekræftet, når den vises som bekræftet på din konto efter registreret betaling eller gyldig kredit. En kvittering sendes, når e-maillevering er tilgængelig. Hvis du er blevet opkrævet, men bookingen ikke er bekræftet, skal du kontakte os før et nyt betalingsforsøg.', 'A booking is confirmed when your account shows it as confirmed after payment or valid credit is recorded. A receipt is sent when email delivery is available. If you were charged but your booking is not confirmed, contact us before trying to pay again.'],
      ['Klubben fastsætter adgang for medlemmer og gæster, bookingvinduer og ordensregler. Tidspunkter skal læses i den tidszone, som vises for banen eller træneren. Sørg for, at du har valgt den rigtige dato, varighed og facilitet.', 'The club sets member and guest access, booking windows and facility rules. Read booking times in the displayed venue or coach time zone. Check the date, duration and facility before confirming.'],
    ]),
    section('cancellation', 'Aflysning og tilbagebetaling', 'Cancellations and refunds', [
      ['For almindelige enkeltbookinger betalt med kort eller wallet giver aflysning mindst 24 timer før start en fuld tilbagebetaling af bookingprisen. Ved senere aflysning eller udeblivelse gives der normalt ingen tilbagebetaling. Fristen beregnes ud fra det bekræftede starttidspunkt, ikke din aktuelle telefonplacering.', 'For ordinary single bookings paid by card or wallet, cancellation at least 24 hours before the confirmed start gives a full refund of the booking price. Later cancellations and no-shows normally receive no refund. The deadline is measured from the confirmed start, not your phone’s current location.'],
      ['Kortbetalinger refunderes til det oprindelige betalingsmiddel. Bankens behandling kan tage flere hverdage. Walletbetalinger føres tilbage som kredit i den samme klubs wallet. Klippekort og trænerpakker returnerer et klip efter deres produktregler; et returneret klip er ikke en ny kontant refundering af den allerede købte pakke.', 'Card payments are refunded to the original payment method; banks may take several business days to process them. Wallet payments return credit to the same club wallet. Court passes and coaching packages return a credit according to their product rules; returning a credit is not a new cash refund of the previously purchased package.'],
      ['Hvis leverandøren aflyser eller ikke kan levere den bookede ydelse, skal du kontakte leverandøren eller RacketBuddy for tilbagebetaling af den ikke-leverede ydelse. Det gælder også, hvis klubben lukker banen på grund af vejr eller baneforhold. Det begrænser ikke lovpligtige rettigheder ved mangler.', 'If the provider cancels or cannot deliver the booked service, contact the provider or RacketBuddy for a refund of the undelivered service. This also covers a venue closure due to weather or court conditions. Statutory remedies for defective services are not restricted.'],
      ['Medlemskaber, hold, sæsonforløb, pakker og køb af walletkredit er særskilte produkter. Se det enkelte tilbud for varighed, kredit, ophør og tilbagebetaling; enkeltbookingens 24-timersregel er ikke en generel afvisning af rettigheder ved disse køb.', 'Memberships, teams, seasonal programmes, packages and wallet top-ups are separate products. Check the offer for duration, credits, termination and refunds; the single-booking 24-hour policy is not a general denial of rights for these purchases.'],
    ]),
    section('wallet', 'Wallet og forudbetalt kredit', 'Wallets and prepaid credit', [
      ['En klubwallet kan kun bruges hos den klub, der udsteder kreditten. Valuta, indbetalt beløb, tildelt kredit og eventuel bonus skal fremgå før køb. Kredit overføres ikke automatisk mellem klubber eller valutaer og er ikke en almindelig bankkonto.', 'A club wallet can be used only with the issuing club. Its currency, payment amount, credited amount and any bonus must be shown before purchase. Credit is not automatically transferred between clubs or currencies and is not a general bank account.'],
      ['Kredit og bonus skal bruges efter de oplyste produktregler. En refundering eller berettiget tilbageførsel af en indbetaling kan medføre, at den tilknyttede kredit og bonus trækkes tilbage. Kontakt klubben eller RacketBuddy om ubrugt kredit, klubbens ophør eller rettigheder til kontant tilbagebetaling. Ufravigelige regler om forudbetaling, gavekort og tilbagebetaling går forud for produktreglerne.', 'Use credit and bonuses according to the disclosed product rules. Refunding or validly reversing a deposit may remove the associated credit and bonus. Contact the club or RacketBuddy about unused credit, a club closure or a right to a cash refund. Mandatory prepaid-credit, gift-card and refund rules prevail over product rules.'],
    ]),
    section('club-subscription', 'Klubabonnement, Custom og godkendelse', 'Club subscriptions, Custom and approval', [
      [`Nye klubber betaler ${monthly} pr. måned for RacketBuddy-abonnementet. Custom koster derudover ${setup} én gang, uanset antal valgte Custom-funktioner. Standard giver standardadministrationen; Custom giver også de valgte moduler. Betalingsgebyrer, hardware og tredjepartsydelser er ikke inkluderet. Bestillingen og betalingssiden viser det samlede beløb og eventuelle skatter før betaling.`, `New clubs pay ${monthly} per month for the RacketBuddy subscription. Custom additionally costs ${setup} once, regardless of the number of selected Custom features. Standard provides standard administration; Custom also provides the selected modules. Processing fees, hardware and third-party services are separate. The order and checkout disclose the total and any applicable taxes before payment.`],
      ['Abonnementet starter ved gennemført betaling og fornyes automatisk hver måned, indtil det opsiges. Den valgte betalingsmetode må opkræves det tydeligt aftalte abonnementsbeløb. Oprettelse og betaling offentliggør ikke klubben automatisk: RacketBuddy skal først godkende den. Betalingsopsætning og eventuelle integrationer skal også færdiggøres.', 'The subscription starts when payment completes and automatically renews monthly until cancelled. The chosen payment method may be charged the clearly agreed subscription amount. Signup and payment do not automatically publish the club: RacketBuddy must approve it first. Payment setup and any integrations must also be completed.'],
      ['Opsig fremtidig fornyelse fra Betaling i klubadministrationen via kundeportalen. Hvis portalen ikke er tilgængelig, kan den bemyndigede administrator opsige ved at skrive til vores kontaktadresse. Send anmodningen før næste fornyelse. Allerede betalte perioder og leveret Custom-arbejde refunderes normalt ikke alene på grund af en opsigelse; rettigheder ved manglende levering eller ufravigelig lovgivning består.', 'Stop future renewals from Payments in club administration through the customer portal. If it is unavailable, an authorised administrator can cancel by emailing our contact address. Submit the request before the next renewal. Paid periods and delivered Custom work are not normally refunded solely because you cancel; remedies for non-delivery and mandatory legal rights remain.'],
      ['Hvis vi afviser klubben før aktivering, ophører abonnementet, og betaling for ikke-leveret oprettelse og service skal afklares og tilbagebetales. Kontakt os med bestillingsoplysninger, hvis du ikke har modtaget besked. Godkendelse er ikke en erklæring om, at klubbens hardware eller et eksternt system er tilsluttet og testet.', 'If we decline the club before activation, the subscription ends and payment for undelivered setup and service must be reconciled and refunded. Contact us with your order details if you have not received confirmation. Approval is not a statement that hardware or an external system has been connected and tested.'],
      ['Klubabonnementer købes af klubben eller virksomheden som led i dens drift. Lovbestemte forbrugerrettigheder gælder stadig for en person, der efter den relevante lov faktisk handler som forbruger.', 'Club subscriptions are purchased for the organisation’s operations. Statutory consumer rights still apply to a person who is legally acting as a consumer.'],
    ]),
    section('coaches-memberships', 'Trænere, medlemskaber og gentagne betalinger', 'Coaches, memberships and recurring purchases', [
      ['Trænere og klubber bestemmer indhold, varighed, niveaukrav og priser i deres tilbud. De er ansvarlige for egne kvalifikationer, tilladelser, forsikringer og skat. En profil eller anmeldelse er ikke en garanti for en faglig certificering.', 'Coaches and clubs set the content, duration, eligibility and prices of their offers. They are responsible for their qualifications, permissions, insurance and taxes. A profile or review is not a guarantee of professional certification.'],
      ['Et spillerprodukt må kun opkræves gentagne gange, når pris, betalingsinterval, fornyelse og opsigelsesmetode er tydeligt oplyst, og køberen har accepteret den gentagne betaling. En enkelt booking indebærer ikke i sig selv et løbende abonnement. Kontakt leverandøren eller RacketBuddy, hvis produktets opsigelse ikke kan findes.', 'A player product may charge repeatedly only when its price, billing interval, renewal and cancellation method are clearly disclosed and the buyer accepts the recurring charge. A single booking does not itself enrol you in an ongoing subscription. Contact the provider or RacketBuddy if you cannot find a product’s cancellation method.'],
    ]),
    section('facilities', 'Lys, adgang og eksterne systemer', 'Lighting, access and external systems', [
      ['Lys og digital døradgang er kun tilgængelige, når klubben har valgt den relevante funktion og tilsluttet kompatibelt udstyr. Klubben bestemmer adgangsvinduet og har ansvar for lovlig installation, lokale sikkerhedsregler, vedligeholdelse og en alternativ adgangsmetode ved fejl. Brug ikke appen som eneste mulighed for nødudgang.', 'Lighting and digital door access are available only when the club selects the relevant feature and connects compatible equipment. The club sets access windows and is responsible for lawful installation, local safety rules, maintenance and a fallback access method. Do not rely on the app as the sole emergency-exit mechanism.'],
      ['Import, synkronisering og forbindelser til andre systemer afhænger af det pågældende systems adgang, rettigheder og tekniske muligheder. Klubben skal have ret til at importere oplysningerne. Et tilbud om Custom er ikke et løfte om direkte API-adgang til ethvert eksternt system.', 'Imports, synchronisation and connections to other systems depend on their access permissions and technical capabilities. The club must have the right to import the data. A Custom offer is not a promise of direct API access to every external system.'],
    ]),
    section('conduct', 'Indhold og brug af platformen', 'Content and platform use', [
      ['Du må ikke tilføje ulovligt indhold, udgive dig for andre, chikanere, kopiere andres personoplysninger eller omgå adgangs- og betalingskontrol. Du bevarer rettigheder til dit eget indhold og giver os den nødvendige tilladelse til at vise og behandle det for at levere platformen.', 'Do not post unlawful content, impersonate others, harass people, copy personal information or bypass access and payment controls. You retain rights to your content and grant us the permission needed to display and process it to provide the platform.'],
      ['Kontakt os for at anmelde ulovligt indhold eller fejl. Vi kan begrænse en konto af hensyn til sikkerhed, lovkrav eller væsentlig misligholdelse og giver en begrundelse og mulighed for at kontakte os, medmindre lovgivning eller sikkerhed kræver andet. En kontobegrænsning ophæver ikke i sig selv berettigede krav om refundering.', 'Contact us to report unlawful content or errors. We may restrict an account for security, legal requirements or material breaches and provide a reason and a way to contact us unless law or security requires otherwise. Restricting an account does not itself remove a valid refund claim.'],
      ['Aftaler mellem medspillere indgås mellem deltagerne. RacketBuddy leverer kontakten, men deltager ikke i kampen eller garanterer, at en anden spiller møder op.', 'Playing-partner arrangements are between the participants. RacketBuddy provides the connection but does not take part in the game or guarantee another player’s attendance.'],
    ]),
    section('privacy', 'Personoplysninger og klubbens data', 'Privacy and club data', [
      ['Privatlivspolitikken beskriver vores behandling af personoplysninger. For kluboplysninger, der behandles på klubbens vegne, gælder databehandleraftalen. Klubben skal have et gyldigt behandlingsgrundlag, informere medlemmer og begrænse sine administratorers adgang.', 'Our Privacy Policy describes personal-data processing. The Data Processing Agreement applies to club data processed on the club’s behalf. Clubs must have a lawful basis, inform members and restrict administrator access.'],
      ['Klubben er ansvarlig for kvaliteten af importerede data og skal planlægge eksport og opbevaring ved systemskift. Kontakt os om dataudlevering og sletning. Lovpligtig dokumentation om betalinger kan skulle opbevares efter et kontoforhold er afsluttet.', 'Clubs are responsible for imported-data quality and should plan export and retention when changing systems. Contact us about data access and deletion. Legally required payment records may need to be retained after an account ends.'],
    ]),
    section('availability-liability', 'Tilgængelighed og ansvar', 'Availability and responsibility', [
      ['Vi tilstræber stabil drift, men vedligeholdelse, netværksfejl og eksterne udbydere kan påvirke tjenesten. Et bestemt aktivitetsniveau, antal kunder, omsætning eller ubrudt tilgængelighed er ikke garanteret. Særskilte skriftlige serviceaftaler gælder, hvis de er indgået.', 'We aim to operate reliably, but maintenance, network failures and external providers can affect service. We do not guarantee a particular activity level, customer count, revenue or uninterrupted availability. Separate written service commitments apply when agreed.'],
      ['Vi er ansvarlige for vores egen levering efter gældende ret. Intet i disse vilkår begrænser ufravigelige forbrugerrettigheder eller ansvar, der ikke lovligt kan begrænses, herunder svig, forsæt, grov uagtsomhed eller relevante personskader. Ansvar for den fysiske sportsydelse ligger hos den leverandør, som leverer den, uden at dette fjerner et ansvar, RacketBuddy selv måtte have.', 'We remain responsible for our own service under applicable law. Nothing limits mandatory consumer rights or liability that cannot lawfully be limited, including fraud, deliberate misconduct, gross negligence or relevant personal injury. The physical sporting service is the provider’s responsibility, without removing any responsibility RacketBuddy itself has.'],
    ]),
    section('changes', 'Ændringer og dokumentversion', 'Changes and document version', [
      ['Disse vilkår gælder nye aftaler fra dokumentets versionsdato. Allerede bekræftede køb følger de aftalte vilkår ved købet. Væsentlige ændringer af et løbende RacketBuddy-abonnement varsles normalt mindst 30 dage før næste berørte fornyelse, og abonnementet kan opsiges før ændringen. Kortere frister kan være nødvendige af lov- eller sikkerhedsgrunde.', 'These terms apply to new agreements from the document’s version date. Confirmed purchases retain the terms agreed at purchase. Material changes to an ongoing RacketBuddy subscription are normally notified at least 30 days before the affected renewal, and the subscription can be cancelled before the change. Legal or security requirements may require shorter notice.'],
      ['En særskilt, skriftligt accepteret aftale om klubben kan supplere disse vilkår. Den kan ikke tilsidesætte rettigheder, som lovgivningen gør ufravigelige.', 'A separately accepted written club agreement may supplement these terms. It cannot override rights that applicable law makes mandatory.'],
    ]),
  ];
  if (region === 'eu') {
    sections.splice(5, 0, section('consumer-rights', 'EU/EØS-forbrugerrettigheder', 'EU/EEA consumer rights', [
      ['Denne version er beregnet til kunder i EU og EØS. Et sprogvalg eller IP-land afgør ikke alene dine juridiske rettigheder. Ufravigelige regler i det land, hvor du som forbruger normalt bor, gælder, når de efter loven skal finde anvendelse.', 'This version is intended for customers in the EU and EEA. A language choice or IP location does not by itself determine legal rights. Mandatory rules of a consumer’s habitual residence apply when the law requires them.'],
      ['Forbrugere har som udgangspunkt 14 dages fortrydelsesret ved fjernkøb af tjenester. Fritidsydelser til en bestemt dato eller periode kan være undtaget; det gælder normalt en konkret banebooking eller sportslektion. Undtagelsen anvendes kun, når det konkrete køb opfylder lovens krav. Den omfatter ikke automatisk alle medlemskaber, walletindbetalinger eller digitale tjenester.', 'Consumers generally have a 14-day withdrawal right for distance service purchases. Leisure services for a specific date or period may be exempt, normally including a dated court booking or sports lesson. The exception applies only where the purchase meets the legal requirements; it does not automatically cover every membership, wallet deposit or digital service.'],
      ['Hvor fortrydelsesret gælder, kan du give os eller leverandøren en tydelig meddelelse inden fristen med navn, bestillingsoplysninger og ønske om at fortryde. Ingen bestemt formular er påkrævet. Opstart af en tjeneste inden fristens udløb kræver de samtykker og oplysninger, loven foreskriver; disse vilkår udgør ikke i sig selv et sådant særskilt samtykke.', 'Where withdrawal applies, send us or the provider a clear notice within the deadline with your name, order details and decision to withdraw. No particular form is required. Starting a service during the withdrawal period requires the disclosures and consents prescribed by law; these terms alone do not constitute that separate consent.'],
    ]));
    sections.push({ ...section('complaints', 'Kontakt og klager', 'Contact and complaints', [
      ['Kontakt først RacketBuddy eller den relevante leverandør med ordrenummer og beskrivelse af problemet. Hvis sagen ikke løses, kan du benytte en kompetent forbrugerklageinstans, hvor den kan behandle sagen. EU-Kommissionens oversigt hjælper med at finde relevante instanser. Vi påstår ikke, at vi deltager i alle klageordninger.', 'First contact RacketBuddy or the relevant provider with the order details and a description of the problem. If unresolved, you may use a competent consumer-dispute body where it can hear the case. The European Commission’s directory helps identify relevant bodies. We do not claim membership of every dispute-resolution scheme.'],
    ]), link: { href: 'https://consumer-redress.ec.europa.eu/dispute-resolution-bodies', label: choose('Forbrugerklageinstanser i Europa', 'Consumer dispute-resolution bodies in Europe') } });
    sections.push(section('law', 'Lovvalg og domstole', 'Applicable law and courts', [
      ['Platformaftalen er underlagt dansk ret, men det fratager ikke en forbruger ufravigelig beskyttelse efter den ret, som ellers ville gælde. Lovbestemte rettigheder til at anlægge sag ved domstolene i forbrugerens hjemland bevares. Disse vilkår pålægger ikke tvungen voldgift eller afkald på kollektive rettigheder.', 'The platform agreement is governed by Danish law, without depriving consumers of mandatory protections under the law that would otherwise apply. Statutory rights to bring proceedings in a consumer’s home courts are preserved. These terms impose no mandatory arbitration or waiver of collective rights.'],
    ]));
  } else {
    sections.splice(5, 0, section('us-rights', '', 'United States consumer and state-law rights', [
      ['', 'This version is intended for United States customers. Federal, state and local consumer laws remain applicable. The 24-hour booking cancellation policy does not restrict a statutory refund, cancellation, warranty or other non-waivable remedy. There is no general promise of a federal 14-day cooling-off period for every online purchase.'],
      ['', 'Any automatic renewal must be clearly disclosed and affirmatively accepted before charging. You may cancel future RacketBuddy club renewals online through the billing portal, or contact us by email if the portal cannot be used. Consumer recurring products must also provide the cancellation information and notices required by applicable law. Merely reading these terms is not separate consent to a recurring charge.'],
      ['', 'Prepaid balances are subject to any applicable state rules on expiration, fees and cash redemption. The club-wallet description does not waive those rights. Contact us or the issuing club about a required redemption or refund.'],
    ]));
    sections.push(section('complaints', '', 'Contact and complaints', [
      ['', 'Contact RacketBuddy or the named provider with your order details and a description of the problem. You may also contact an applicable state consumer-protection agency or attorney general, or pursue rights through a competent court. These terms do not prevent reporting to regulators or making a valid payment dispute.'],
    ]));
    sections.push(section('law', '', 'Applicable law and courts', [
      ['', 'The platform agreement is governed by Delaware law, to the extent lawful, without overriding mandatory federal or state consumer protections. Business disputes may be brought before competent courts in Delaware. Consumers retain any non-waivable rights to a different law or forum. There is no mandatory arbitration clause, jury-trial waiver or class-action waiver in these terms.'],
    ]));
  }
  return sections;
}
