'use client';
import {useState} from 'react';
import {useFormState} from 'react-dom';
import {registerClub} from '../../lib/club-onboarding-actions';
import {CUSTOM_FEATURES} from '../../lib/club-features';
import {SPORTS,sportLabel} from '../../lib/sports';
import {SubmitButton} from '../../components/SubmitButton';
export function SignupForm({prices}:{prices:{standard:number;custom:number|null}}){
 const [mode,setMode]=useState('STANDARD'),[sports,setSports]=useState<string[]>(['TENNIS']),[state,action]=useFormState(registerClub,null);const price=mode==='CUSTOM'?prices.custom:prices.standard;
 return <form action={action} className="space-y-6"><section className="card space-y-4"><h2 className="display text-2xl">1. Vælg jeres løsning</h2><div className="grid gap-3 sm:grid-cols-2">{[['STANDARD','Standard',prices.standard],['CUSTOM','Custom',prices.custom]].map(([id,label,p])=><label key={id} className={`rounded-2xl border p-4 cursor-pointer ${mode===id?'border-court bg-court/5':'border-slate/20'}`}><input type="radio" name="mode" value={id??''} checked={mode===id} onChange={()=>setMode(String(id))}/> <strong>{label}</strong><p className="mt-2">{p==null?'Pris ikke offentliggjort':id==='CUSTOM'?`${Number(p).toLocaleString('da-DK')} kr. én gang + ${prices.standard} kr./måned`:`${p} kr./måned`}</p><p className="text-sm text-slate mt-1">{id==='STANDARD'?'Standard klubadministration med baner, bookinger og betaling.':'Standardadministration plus de funktioner, I vælger nedenfor. Engangsprisen er den samme uanset antal funktioner.'}</p></label>)}</div>{mode==='CUSTOM'&&<div className="grid gap-3 sm:grid-cols-2">{CUSTOM_FEATURES.map(f=><label key={f.id} className="flex gap-3 rounded-xl border border-slate/15 p-3"><input type="checkbox" name="features" value={f.id}/>{f.label}</label>)}</div>}<input type="hidden" name="quote" value={price??''}/></section>
 <section className="card space-y-4"><h2 className="display text-2xl">2. Klub og baner</h2><div className="grid gap-4 sm:grid-cols-2">{[['name','Klubbens navn'],['city','By'],['contact','Dit navn']].map(([name,label])=><label className="label" key={name}>{label}<input className="input" name={name} required maxLength={150}/></label>)}<label className="label">Banepris pr. time (kr.)<input className="input" name="priceHour" type="number" min="0" max="10000" defaultValue="80" required/></label></div><p className="text-sm text-slate">Vælg sportsgrene og antal baner eller borde. I kan ændre navne, underlag, priser og åbningstider i administrationen.</p><div className="grid gap-3 sm:grid-cols-2">{SPORTS.map(s=><div key={s} className="rounded-xl border border-slate/15 p-3"><label className="flex gap-2"><input type="checkbox" name="sports" value={s} checked={sports.includes(s)} onChange={e=>setSports(e.target.checked?[...sports,s]:sports.filter(x=>x!==s))}/>{sportLabel(s,'da')}</label>{sports.includes(s)&&<label className="label mt-2 block">Antal {s==='BORDTENNIS'?'borde':'baner'}<input className="input" name={'count_'+s} type="number" min="1" max="30" defaultValue="1" required/></label>}</div>)}</div></section>
 <section className="card space-y-4"><h2 className="display text-2xl">3. Opret klublogin</h2><label className="label block">E-mail<input className="input" name="email" type="email" autoComplete="email" required/></label><label className="label block">Adgangskode<input className="input" name="password" type="password" autoComplete="new-password" minLength={10} maxLength={72} required/></label><p className="text-sm text-slate">Brug mindst 10 tegn. Det samme login virker på hjemmesiden og under Klublogin i appen.</p><label className="flex items-start gap-3 text-sm"><input className="mt-1" type="checkbox" name="terms" required/><span>Jeg må oprette klubben og accepterer <a className="underline" href="/vilkaar" target="_blank" rel="noreferrer">handelsbetingelserne</a> og <a className="underline" href="/databehandleraftale" target="_blank" rel="noreferrer">databehandleraftalen</a>. {mode==='CUSTOM'&&<>Custom koster {price?.toLocaleString('da-DK')??'—'} kr. i engangsbetaling, uanset antal funktioner. </>}Abonnementet på {prices.standard} kr./måned starter ved betaling og fornyes månedligt indtil opsigelse. Klubben offentliggøres først efter RacketBuddys godkendelse.</span></label>{state?.error&&<p role="alert" className="text-court font-semibold">{state.error}</p>}<SubmitButton className="btn-court w-full" disabled={price==null} pendingText="Opretter klub…">Opret klub og fortsæt til betaling</SubmitButton>{price==null&&<p>Custom-prisen skal offentliggøres af RacketBuddy, før I kan tilmelde jer.</p>}</section>
 </form>;
}
