'use client';
import {useState} from 'react';
import {useFormState} from 'react-dom';
import {registerClub} from '../../lib/club-onboarding-actions';
import {CUSTOM_FEATURES} from '../../lib/club-features';
import {SPORTS,sportLabel,type Locale} from '../../lib/sports';
import {MARKETS,CURRENCIES,TIME_ZONES,countryLabel,marketFor,formatMoney} from '../../lib/international';
import {phrase} from '../../lib/phrases';
import {SubmitButton} from '../../components/SubmitButton';
export function SignupForm({prices,locale='da',initialCountry='DK'}:{prices:{standard:number;custom:number|null};locale?:Locale;initialCountry?:string}){
 const [mode,setMode]=useState('STANDARD'),[sports,setSports]=useState<string[]>(['TENNIS']),[state,action]=useFormState(registerClub,null);
 const [country,setCountry]=useState(initialCountry),[currency,setCurrency]=useState(marketFor(initialCountry)?.currency??'DKK'),[timeZone,setTimeZone]=useState(marketFor(initialCountry)?.timeZone??'Europe/Copenhagen');
 const da=locale==='da',f=(d:string,e:string)=>da?d:e,price=mode==='CUSTOM'?prices.custom:prices.standard,money=(p:number)=>formatMoney(p,'DKK',locale);
 return <form action={action} className="space-y-6"><input type="hidden" name="locale" value={locale}/>
 <section className="card space-y-4"><h2 className="display text-2xl">{f('1. Vælg jeres løsning','1. Choose your plan')}</h2><div className="grid gap-3 sm:grid-cols-2">{[['STANDARD','Standard',prices.standard],['CUSTOM','Custom',prices.custom]].map(([id,label,p])=><label key={id} className={`rounded-2xl border p-4 cursor-pointer ${mode===id?'border-court bg-court/5':'border-slate/20'}`}><input type="radio" name="mode" value={id??''} checked={mode===id} onChange={()=>setMode(String(id))}/> <strong>{label}</strong><p className="mt-2">{p==null?f('Pris ikke offentliggjort','Price not available'):id==='CUSTOM'?`${money(Number(p))} ${f('én gang','once')} + ${money(prices.standard)}/${f('måned','month')}`:`${money(Number(p))}/${f('måned','month')}`}</p><p className="text-sm text-slate mt-1">{id==='STANDARD'?f('Standard klubadministration med baner, bookinger og betaling.','Standard club management with courts, bookings and payments.'):f('Standardadministration plus de funktioner, I vælger nedenfor. Engangsprisen er den samme uanset antal funktioner.','Standard management plus the features you select below. The setup price is fixed, regardless of how many features you select.')}</p></label>)}</div>{mode==='CUSTOM'&&<div className="grid gap-3 sm:grid-cols-2">{CUSTOM_FEATURES.map(feature=><label key={feature.id} className="flex gap-3 rounded-xl border border-slate/15 p-3"><input type="checkbox" name="features" value={feature.id}/>{phrase(feature.label,locale)}</label>)}</div>}<input type="hidden" name="quote" value={price??''}/></section>
 <section className="card space-y-4"><h2 className="display text-2xl">{f('2. Klub og baner','2. Club and courts')}</h2><div className="grid gap-4 sm:grid-cols-2">
 <label className="label">{f('Land','Country')}<select className="input" name="country" value={country} onChange={e=>{setCountry(e.target.value);const m=marketFor(e.target.value)!;setCurrency(m.currency);setTimeZone(m.timeZone);}}>{MARKETS.map(m=><option key={m.code} value={m.code}>{countryLabel(m.code,locale)}</option>)}</select></label>
 <label className="label">{f('Valuta for klubbookinger','Currency for club bookings')}<select className="input" name="currency" value={currency} onChange={e=>setCurrency(e.target.value)}>{CURRENCIES.map(c=><option key={c}>{c}</option>)}</select></label>
 <label className="label sm:col-span-2">{f('Klubbens tidszone','Venue time zone')}<select className="input" name="timeZone" value={timeZone} onChange={e=>setTimeZone(e.target.value)}>{TIME_ZONES.map(z=><option key={z}>{z}</option>)}</select></label>
 {[['name',f('Klubbens navn','Club name')],['city',f('By','City')],['address',f('Adresse','Address')],['contact',f('Dit navn','Your name')]].map(([name,label])=><label className="label" key={name}>{label}<input className="input" name={name} required maxLength={150}/></label>)}
 <label className="label">{f('Banepris pr. time','Court price per hour')} ({currency})<input className="input" name="priceHour" type="number" min="0" max="10000" defaultValue="80" required/></label></div>
 <p className="text-sm text-slate">{f('Vælg sportsgrene og antal baner eller borde. I kan ændre navne, underlag, priser og åbningstider i administrationen.','Choose sports and the number of courts or tables. You can edit names, surfaces, prices and opening hours in your administration.')}</p>
 <div className="grid gap-3 sm:grid-cols-2">{SPORTS.map(s=><div key={s} className="rounded-xl border border-slate/15 p-3"><label className="flex gap-2"><input type="checkbox" name="sports" value={s} checked={sports.includes(s)} onChange={e=>setSports(e.target.checked?[...sports,s]:sports.filter(x=>x!==s))}/>{sportLabel(s,locale)}</label>{sports.includes(s)&&<label className="label mt-2 block">{s==='BORDTENNIS'?f('Antal borde','Number of tables'):f('Antal baner','Number of courts')}<input className="input" name={'count_'+s} type="number" min="1" max="30" defaultValue="1" required/></label>}</div>)}</div></section>
 <section className="card space-y-4"><h2 className="display text-2xl">{f('3. Opret klublogin','3. Create your club login')}</h2><label className="label block">E-mail<input className="input" name="email" type="email" autoComplete="email" required/></label><label className="label block">{f('Adgangskode','Password')}<input className="input" name="password" type="password" autoComplete="new-password" minLength={10} maxLength={72} required/></label><p className="text-sm text-slate">{f('Brug mindst 10 tegn. Det samme login virker på hjemmesiden og under Klublogin i appen.','Use at least 10 characters. The same login works on the website and under Club login in the app.')}</p>
 <label className="flex items-start gap-3 text-sm"><input className="mt-1" type="checkbox" name="terms" required/><span>{f('Jeg må oprette klubben og accepterer','I am authorised to register the club and accept the')} <a className="underline" href="/vilkaar" target="_blank" rel="noreferrer">{f('handelsbetingelserne','terms')}</a> {f('og','and')} <a className="underline" href="/databehandleraftale" target="_blank" rel="noreferrer">{f('databehandleraftalen','data processing agreement')}</a>. {mode==='CUSTOM'&&`${f('Custom koster','Custom costs')} ${price==null?'—':money(price)} ${f('én gang, uanset antal funktioner.','once, regardless of the selected features.')} `}{f('Abonnementet på','The subscription of')} {money(prices.standard)}/{f('måned starter ved betaling og fornyes månedligt indtil opsigelse. Klubben offentliggøres først efter RacketBuddys godkendelse.','month starts on payment and renews monthly until cancelled. Your club goes live after RacketBuddy approval.')}</span></label>
 {state?.error&&<p role="alert" className="text-court font-semibold">{phrase(state.error,locale)}</p>}<SubmitButton className="btn-court w-full" disabled={price==null} pendingText={f('Opretter klub…','Creating club…')}>{f('Opret klub og fortsæt til betaling','Create club and continue to payment')}</SubmitButton>{price==null&&<p>{f('Custom-prisen skal offentliggøres af RacketBuddy, før I kan tilmelde jer.','The Custom price must be published before signup is available.')}</p>}</section>
 </form>;
}
