'use client';
import {useFormState,useFormStatus} from 'react-dom';
import {useState} from 'react';
import {previewResasports} from '../../lib/resasports-actions';
import {resaCsv,type ResaSnapshot} from '../../lib/resasports';
import {ImportForm} from './ImportForm';
function FetchButton(){const {pending}=useFormStatus();return <button disabled={pending} className="btn-court">{pending?'Henter data …':'Hent fra Resasports'}</button>;}
function MapImport({snapshot,courts}:{snapshot:ResaSnapshot;courts:{id:string;name:string}[]}){
 const [mapping,setMapping]=useState<Record<string,string>>({}),[csv,setCsv]=useState(''),[error,setError]=useState('');
 const used=snapshot.facilities.filter(f=>snapshot.bookings.some(b=>b.facilityId===f.id));
 return <div className="space-y-4"><p>Hentet fra Resasports-klub {snapshot.applicationId}: {snapshot.members.length} medlemmer og {snapshot.bookings.length} bookinger.</p><p className="text-sm text-slate">Kontrollér klub-ID, medlemmer og bookingtider nedenfor. Gamle betalinger, kontingenter og wallet-saldi overføres ikke. Dette er en engangsimport; senere ændringer og aflysninger i Resasports bliver ikke synkroniseret.</p>
 {used.map(f=><label className="label block" key={f.id}>{f.name} (Resasports #{f.id})<select className="input" value={mapping[f.id]??''} onChange={e=>{setCsv('');setMapping({...mapping,[f.id]:e.target.value});}}><option value="">Vælg tilsvarende bane</option>{courts.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></label>)}
 <details><summary className="cursor-pointer font-semibold">Gennemse hentede data</summary><div className="max-h-80 overflow-auto text-sm"><table className="w-full"><caption className="text-left">Medlemmer</caption><thead><tr><th>Navn</th><th>E-mail</th><th>Telefon</th></tr></thead><tbody>{snapshot.members.map(m=><tr key={m.id}><td>{m.name}</td><td>{m.email}</td><td>{m.phone}</td></tr>)}</tbody></table><table className="w-full mt-4"><caption className="text-left">Bookinger (dansk tid)</caption><thead><tr><th>ID</th><th>Medlem</th><th>Bane</th><th>Fra – til</th></tr></thead><tbody>{snapshot.bookings.map(b=><tr key={b.id}><td>{b.id}</td><td>{snapshot.members.find(m=>m.id===b.userId)?.name}</td><td>{snapshot.facilities.find(f=>f.id===b.facilityId)?.name}</td><td>{new Date(b.start).toLocaleString('da-DK',{timeZone:'Europe/Copenhagen'})} – {new Date(b.end).toLocaleString('da-DK',{timeZone:'Europe/Copenhagen'})}</td></tr>)}</tbody></table></div></details>
 <button className="btn-ghost" onClick={()=>{try{setCsv(resaCsv(snapshot,mapping));setError('');}catch(e){setError((e as Error).message);}}}>Klargør import</button>{error&&<p role="alert">{error}</p>}{csv&&<ImportForm key={csv} initialCsv={csv} initialSource={`Resasports:${snapshot.applicationId}`}/>}
 </div>;
}
export function ResasportsForm({courts}:{courts:{id:string;name:string}[]}){
 const [state,action]=useFormState(previewResasports,null);
 return <section className="card space-y-4"><h2 className="display text-2xl">Hent direkte fra Resasports</h2><p className="text-sm text-slate">Brug API-adgang udleveret af Nubapp, ikke dit almindelige medlemslogin. Bed om læseadgang til getUsers, getFacilities og getBookings i API v4. Denne ældre API kræver særskilt godkendelse. Oplysningerne bruges kun til dette opslag og gemmes ikke.</p>
 <form action={action} className="space-y-3"><div className="grid gap-3 sm:grid-cols-2">{[['username','API-bruger','text'],['password','API-adgangskode','password'],['applicationId','Resasports klub-ID','text'],['actorId','Resasports administrator-ID','text'],['token','Token (hvis Nubapp kræver det)','password']].map(([name,label,type])=><label className="label" key={name}>{label}<input className="input" name={name} type={type} autoComplete="off" required={name!=='token'}/></label>)}<label className="label">Miljø<select className="input" name="environment"><option value="production">Klubbens Resasports</option><option value="sandbox">Nubapp sandbox</option></select></label><label className="label">Bookinger fra<input name="from" type="date" className="input" required/></label><label className="label">Bookinger til<input name="to" type="date" className="input" required/></label></div><label className="flex gap-2 text-sm"><input type="checkbox" name="danishTime" required/>Klubbens Resasports-bookinger er angivet i dansk tid (Europe/Copenhagen).</label><p className="text-sm text-slate">Højst 500 medlems- og bookingrækker samlet. Vælg fremtidige bookinger, højst ét år frem. Sandbox kan indeholde en kopi af rigtige klubdata. Ingen data ændres hos Resasports.</p><FetchButton/></form>
 {state?.error&&<p role="alert">{state.error}</p>}{state?.snapshot&&<MapImport key={JSON.stringify(state.snapshot)} snapshot={state.snapshot} courts={courts}/>}
 </section>;
}
