'use client';import { useWebsiteInternational } from "../../components/InternationalProvider";
import { useFormState, useFormStatus } from 'react-dom';
import { useState } from 'react';
import { previewResasports } from '../../lib/resasports-actions';
import { resaCsv, type ResaSnapshot } from '../../lib/resasports';
import { ImportForm } from './ImportForm';
function FetchButton() {const { tr, money, currency, timeZone,locale } = useWebsiteInternational();const { pending } = useFormStatus();return <button disabled={pending} className="btn-court">{pending ? tr('Henter data …') : tr('Hent fra Resasports')}</button>;}
function MapImport({ snapshot, courts }: {snapshot: ResaSnapshot;courts: {id: string;name: string;}[];}) {const { tr, money, currency, timeZone,locale } = useWebsiteInternational();
  const [mapping, setMapping] = useState<Record<string, string>>({}),[csv, setCsv] = useState(''),[error, setError] = useState('');
  const used = snapshot.facilities.filter((f) => snapshot.bookings.some((b) => b.facilityId === f.id));
  return <div className="space-y-4"><p>{tr("Hentet fra Resasports-klub") + " "}{snapshot.applicationId}: {snapshot.members.length}{" " + tr("medlemmer og") + " "}{snapshot.bookings.length}{" " + tr("bookinger.")}</p><p className="text-sm text-slate">{tr("Kontroll\xE9r klub-ID, medlemmer og bookingtider nedenfor. Gamle betalinger, kontingenter og wallet-saldi overf\xF8res ikke. Dette er en engangsimport; senere \xE6ndringer og aflysninger i Resasports bliver ikke synkroniseret.")}</p>
 {used.map((f) => <label className="label block" key={f.id}>{f.name}{" " + tr("(Resasports #")}{f.id})<select className="input" value={mapping[f.id] ?? ''} onChange={(e) => {setCsv('');setMapping({ ...mapping, [f.id]: e.target.value });}}><option value="">{tr("V\xE6lg tilsvarende bane")}</option>{courts.map((c) => <option key={c.id} value={c.name}>{c.name}</option>)}</select></label>)}
 <details><summary className="cursor-pointer font-semibold">{tr("Gennemse hentede data")}</summary><div className="max-h-80 overflow-auto text-sm"><table className="w-full"><caption className="text-left">{tr("Medlemmer")}</caption><thead><tr><th>{tr("Navn")}</th><th>{tr("E-mail")}</th><th>{tr("Telefon")}</th></tr></thead><tbody>{snapshot.members.map((m) => <tr key={m.id}><td>{m.name}</td><td>{m.email}</td><td>{m.phone}</td></tr>)}</tbody></table><table className="w-full mt-4"><caption className="text-left">{tr("Bookinger (lokal tid)")}</caption><thead><tr><th>{tr("ID")}</th><th>{tr("Medlem")}</th><th>{tr("Bane")}</th><th>{tr("Fra \u2013 til")}</th></tr></thead><tbody>{snapshot.bookings.map((b) => <tr key={b.id}><td>{b.id}</td><td>{snapshot.members.find((m) => m.id === b.userId)?.name}</td><td>{snapshot.facilities.find((f) => f.id === b.facilityId)?.name}</td><td>{new Date(b.start).toLocaleString(locale, { timeZone: snapshot.timeZone??timeZone })} – {new Date(b.end).toLocaleString(locale, { timeZone: snapshot.timeZone??timeZone })}</td></tr>)}</tbody></table></div></details>
 <button className="btn-ghost" onClick={() => {try {setCsv(resaCsv(snapshot, mapping));setError('');} catch (e) {setError((e as Error).message);}}}>{tr("Klarg\xF8r import")}</button>{error && <p role="alert">{error}</p>}{csv && <ImportForm key={csv} initialCsv={csv} initialSource={`Resasports:${snapshot.applicationId}`} />}
 </div>;
}
export function ResasportsForm({ courts }: {courts: {id: string;name: string;}[];}) {const { tr, money, currency, timeZone,locale } = useWebsiteInternational();
  const [state, action] = useFormState(previewResasports, null);
  return <section className="card space-y-4"><h2 className="display text-2xl">{tr("Hent direkte fra Resasports")}</h2><p className="text-sm text-slate">{tr("Brug API-adgang udleveret af Nubapp, ikke dit almindelige medlemslogin. Bed om l\xE6seadgang til getUsers, getFacilities og getBookings i API v4. Denne \xE6ldre API kr\xE6ver s\xE6rskilt godkendelse. Oplysningerne bruges kun til dette opslag og gemmes ikke.")}</p>
 <form action={action} className="space-y-3"><div className="grid gap-3 sm:grid-cols-2">{[['username', 'API-bruger', 'text'], ['password', 'API-adgangskode', 'password'], ['applicationId', 'Resasports klub-ID', 'text'], ['actorId', 'Resasports administrator-ID', 'text'], ['token', 'Token (hvis Nubapp kræver det)', 'password']].map(([name, label, type]) => <label className="label" key={name}>{tr(label)}<input className="input" name={name} type={type} autoComplete="off" required={name !== 'token'} /></label>)}<label className="label">{tr("Milj\xF8")}<select className="input" name="environment"><option value="production">{tr("Klubbens Resasports")}</option><option value="sandbox">{tr("Nubapp sandbox")}</option></select></label><label className="label">{tr("Bookinger fra")}<input name="from" type="date" className="input" required /></label><label className="label">{tr("Bookinger til")}<input name="to" type="date" className="input" required /></label></div><label className="flex gap-2 text-sm"><input type="checkbox" name="venueTime" required />{tr("Resasports bruger klubbens lokale tidszone:")}{timeZone}</label><p className="text-sm text-slate">{tr("H\xF8jst 500 medlems- og bookingr\xE6kker samlet. V\xE6lg fremtidige bookinger, h\xF8jst \xE9t \xE5r frem. Sandbox kan indeholde en kopi af rigtige klubdata. Ingen data \xE6ndres hos Resasports.")}</p><FetchButton /></form>
 {state?.error && <p role="alert">{tr(state.error)}</p>}{state?.snapshot && <MapImport key={JSON.stringify(state.snapshot)} snapshot={state.snapshot} courts={courts} />}
 </section>;
}
