export type Market = { code: string; name: string; currency: string; defaultLocale: string; timeZone: string; center: number[]; live: boolean; flag: string };
export const MARKETS: Market[];
export const CURRENCIES: string[];
export const LANGUAGES: string[];
export const LANGUAGE_NAMES: Record<string,string>;
export const TIME_ZONES: string[];
export function marketFor(code: unknown): Market | null;
export function validLocale(locale: unknown): boolean;
export function validCurrency(currency: unknown): boolean;
export function validTimeZone(zone: unknown): boolean;
export function countryLabel(code: string, locale?: string): string;
export function numberLocale(locale?: string): string;
export function formatMoney(amount: number, currency?: string, locale?: string): string;
export function toMinor(amount: number, currency?: string): number;
export function formatDate(instant: string | number | Date, locale?: string, timeZone?: string, options?: Intl.DateTimeFormatOptions): string;
export function wallParts(instant: string | number | Date, timeZone?: string): {year:number;month:number;day:number;hour:number;minute:number;second:number;weekday:number};
export function dayKey(instant: string | number | Date, timeZone?: string): string;
export function addCalendarDays(key: string, amount: number): string;
export function wallTimeCandidates(key:string,hour?:number,minute?:number,timeZone?:string):Date[];
export function wallTime(key: string, hour?: number, minute?: number, timeZone?: string): Date | null;
export function localInputDate(value: unknown, timeZone?: string): Date;
export function calendarDays(from: Date, until: Date, timeZone?: string): string[];
