import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import {execFileSync} from 'node:child_process';
import {PGlite} from '@electric-sql/pglite';
import {PGLiteSocketServer} from '@electric-sql/pglite-socket';
import {PrismaClient} from '@prisma/client';
import {loadIsolatedModule} from '../src/lib/testing/isolated-module';
import * as features from '../src/lib/club-features';
import * as sports from '../src/lib/sports';
import * as courtSports from '../src/lib/club-sports';
async function main(){
 const pg=await PGlite.create();await pg.exec(execFileSync(process.execPath,['node_modules/prisma/build/index.js','migrate','diff','--from-empty','--to-schema-datamodel','prisma/schema.prisma','--script'],{encoding:'utf8'}));
 const server=new PGLiteSocketServer({db:pg,host:'127.0.0.1',port:0});await server.start();
 const db=new PrismaClient({datasources:{db:{url:`postgresql://postgres:postgres@${server.getServerConn()}/postgres?connection_limit=1&sslmode=disable`}}});
 let count=0;const pass=(s:string)=>{count++;console.log('PASS '+s);};let creates=0,customerCreates=0,cancellations=0,webhookReady=true,session:any,sub:any,signedIn:string|null=null;
 const settings={appUrl:'https://example.invalid',stripeSecretKey:'test-only',stripeWebhookSecret:'test-only'};
 const client={customers:{create:async(_args:any,opts:any)=>{assert.ok(opts.idempotencyKey);customerCreates++;return{id:'cus_local'};}},checkout:{sessions:{retrieve:async()=>session,create:async(args:any,opts:any)=>{creates++;assert.ok(opts.idempotencyKey);assert.equal(args.mode,'subscription');assert.equal(args.line_items[0].price_data.unit_amount,1499500);assert.equal(args.line_items[0].price_data.recurring,undefined);assert.equal(args.line_items[1].price_data.unit_amount,19900);assert.equal(args.line_items[1].price_data.recurring.interval,'month');session={id:'cs_local',url:'https://checkout.stripe.com/synthetic',status:'open',mode:'subscription',customer:'cus_local',client_reference_id:args.client_reference_id,subscription:null};return session;}}},subscriptions:{retrieve:async()=>sub,cancel:async(id:string)=>{assert.equal(id,'sub_local');cancellations++;sub.status='canceled';return sub;}}};
 const service=loadIsolatedModule('src/lib/club-onboarding.ts',{'./webhook-setup':{inspectWebhook:async()=>({status:webhookReady?'ok':'fejl'})},'./db':{db},'./stripe':{stripe:async()=>client},'./settings':{getSettings:async()=>settings}});
 const actions=loadIsolatedModule('src/lib/club-onboarding-actions.ts',{'./webhook-setup':{},'./geocode':{geocode:async(_address:string,_city:string,country:string)=>{assert.equal(country,'US');return{latitude:34.05,longitude:-118.25};}},'node:crypto':crypto,bcryptjs:bcrypt,'next/navigation':{redirect:(url:string)=>{throw Error(`REDIRECT:${url}`);}},'next/cache':{revalidatePath(){}},'./db':{db},'./session':{createSession:async(id:string)=>{signedIn=id;},getCurrentUser:async()=>signedIn?db.user.findUnique({where:{id:signedIn}}):null},'./club-onboarding':service,'./club-features':features,'./sports':sports,'./club-sports':courtSports});
 try{
  assert.deepEqual(await service.clubSignupPrices(),{standard:199,custom:14995});pass('Owner price: Custom 14995 once plus 199 monthly');
  await db.platformSetting.create({data:{key:'clubSignupPricesV2',value:JSON.stringify({standard:199,custom:14995})}});
  const f=new FormData();for(const[k,v]of Object.entries({email:'club@example.invalid',password:'synthetic-password',name:'Test padel club',city:'Test',contact:'Test Admin',mode:'CUSTOM',terms:'on',quote:'14995',priceHour:'120',count_PADEL:'4'}))f.set(k,v);f.append('features','lys-adgang');f.append('features','medlemmer');f.append('sports','PADEL');
  await assert.rejects(actions.registerClub(null,f),/REDIRECT:\/club-start/);assert.ok(signedIn);const u=await db.user.findUniqueOrThrow({where:{id:signedIn!}});assert.ok(await bcrypt.compare('synthetic-password',u.passwordHash));let club=await db.club.findUniqueOrThrow({where:{id:u.clubId!}});assert.equal(club.status,'PENDING');assert.equal(club.subscriptionKr,199);assert.equal(club.signupSetupKr,14995);assert.equal(await db.court.count({where:{clubId:club.id,sport:'PADEL'}}),4);pass('Registration creates own login, four padel courts and pending club atomically');
  assert.equal(features.clubHasSection('CUSTOM','lys-adgang',club.customFeatures),true);assert.equal(features.clubHasSection('CUSTOM','hjemmeside',club.customFeatures),false);assert.equal(features.clubHasSection('STANDARD','lys-adgang',club.customFeatures),false);pass('Custom menu exposes only selected modules; Standard stays standard');
  const management=loadIsolatedModule('src/lib/club-management-actions.ts',{'./webhook-setup':{},'node:crypto':crypto,bcryptjs:bcrypt,'next/cache':{},'./db':{db},'./session':{getCurrentUser:async()=>u},'./club-features':features});await management.requireCustomClub('lys-adgang');await assert.rejects(management.requireCustomClub('priser'),/ikke valgt/);pass('Backend refuses unselected modules even when called directly');
  assert.ok((await actions.registerClub(null,f)).error);assert.equal(await db.club.count(),1);pass('Duplicate signup cannot overwrite an existing account or create an orphan club');
  f.set('email','bad-price@example.invalid');f.set('quote','1');assert.ok((await actions.registerClub(null,f)).error);assert.equal(await db.club.count(),1);pass('Client cannot change the quoted subscription price');
  webhookReady=false;await assert.rejects(service.startOnboardingCheckout(club.id),/opsætning/);assert.equal(creates,0);webhookReady=true;pass('Missing webhook configuration blocks checkout before any charge');
  assert.equal(await service.startOnboardingCheckout(club.id),'https://checkout.stripe.com/synthetic');assert.equal(await service.startOnboardingCheckout(club.id),'https://checkout.stripe.com/synthetic');assert.equal(creates,1);assert.equal(customerCreates,1);pass('Checkout retries reuse one customer and one open session');
  await assert.rejects(service.approvePaidSignup(club.id),/betalt abonnement/);assert.equal((await db.club.findUniqueOrThrow({where:{id:club.id}})).status,'PENDING');pass('An open/unpaid checkout cannot approve or publish the club');
  session={...session,status:'complete',subscription:'sub_local'};sub={id:'sub_local',status:'active',customer:'cus_local',metadata:{clubId:club.id},items:{data:[{quantity:1,current_period_end:Math.floor(Date.now()/1000)+86400,price:{currency:'dkk',unit_amount:19900,recurring:{interval:'month',interval_count:1}}}]},latest_invoice:{status:'open',currency:'dkk',amount_paid:0}};
  await assert.rejects(service.approvePaidSignup(club.id),/betalt abonnement/);pass('Active subscription alone is insufficient without paid invoice');
  sub.latest_invoice={status:'paid',currency:'dkk',amount_paid:1519400};await assert.rejects(service.approvePaidSignup(club.id),/betalt abonnement/);session.payment_status='paid';session.currency='dkk';session.amount_total=1519400;await service.refreshClubSignup(club.id);assert.equal((await db.club.findUniqueOrThrow({where:{id:club.id}})).status,'PENDING');await service.approvePaidSignup(club.id);await service.approvePaidSignup(club.id);assert.equal((await db.club.findUniqueOrThrow({where:{id:club.id}})).status,'APPROVED');pass('Paid club awaits approval; one approval publishes it and retry is safe');
  await assert.rejects(service.startOnboardingCheckout(club.id),/allerede et abonnement/);assert.equal(creates,1);pass('Paid club cannot accidentally buy a second subscription');
  assert.ok((await db.club.findUniqueOrThrow({where:{id:club.id}})).signupSetupPaidAt);sub.latest_invoice.amount_paid=19900;sub.status='past_due';sub.latest_invoice.status='open';await service.refreshClubSignup(club.id);assert.equal((await db.club.findUniqueOrThrow({where:{id:club.id}})).status,'SUSPENDED');sub.status='active';sub.latest_invoice.status='paid';await service.refreshClubSignup(club.id);assert.equal((await db.club.findUniqueOrThrow({where:{id:club.id}})).status,'APPROVED');pass('Failed payment suspends publication; verified recovery restores approved club');
  sub.customer='cus_wrong';await assert.rejects(service.refreshClubSignup(club.id),/tilknytning/);sub.customer='cus_local';sub.items.data[0].price.unit_amount=100;await assert.rejects(service.refreshClubSignup(club.id),/pris/);sub.items.data[0].price.unit_amount=19900;pass('Foreign customer and wrong subscription amount are rejected');
  await service.rejectPaidSignup(club.id,'Test rejection');assert.equal(cancellations,1);sub.status='active';await service.refreshClubSignup(club.id);assert.equal((await db.club.findUniqueOrThrow({where:{id:club.id}})).status,'REJECTED');await assert.rejects(service.approvePaidSignup(club.id),/betalt abonnement/);pass('Payment notifications cannot republish a rejected club');
  f.set('email','standard@example.invalid');f.set('mode','STANDARD');f.set('quote','199');await assert.rejects(actions.registerClub(null,f),/REDIRECT/);const standard=await db.club.findFirstOrThrow({where:{contactEmail:'standard@example.invalid'}});assert.equal(standard.solutionMode,'STANDARD');assert.equal(standard.customFeatures,'[]');assert.equal(standard.subscriptionKr,199);assert.equal(standard.signupSetupKr,0);pass('Standard registration discards custom choices and freezes Standard price');
  f.set('email','us-club@example.invalid');f.set('country','US');f.set('currency','USD');f.set('timeZone','America/Los_Angeles');f.set('locale','en-US');f.set('address','100 Test Street');f.set('city','Los Angeles');
  await assert.rejects(actions.registerClub(null,f),/REDIRECT/);const international=await db.club.findFirstOrThrow({where:{contactEmail:'us-club@example.invalid'}});const internationalAdmin=await db.user.findFirstOrThrow({where:{clubId:international.id,role:'CLUB_ADMIN'}});
  assert.equal(international.currency,'USD');assert.equal(international.timeZone,'America/Los_Angeles');assert.equal(international.country,'US');assert.equal(international.latitude,34.05);assert.equal(internationalAdmin.locale,'en-US');assert.equal(internationalAdmin.country,'US');assert.equal(international.subscriptionKr,199);assert.equal(international.signupSetupKr,0);pass('US signup stores USD, venue zone, coordinates and login language while retaining DKK platform tariff');
  console.log(`PASS ${count} onboarding scenarios; Stripe is simulated, no real charges.`);
 }finally{await db.$disconnect();await server.stop();await new Promise<void>(r=>setImmediate(r));await new Promise<void>(r=>setImmediate(r));await pg.close();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
