name: EAS iOS Build Direct

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/eas-build-submit-ios.yml"

permissions:
  contents: read

jobs:
  eas-build-ios:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - run: npm ci
      - name: Link existing EAS project
        run: npx eas-cli@latest init --id 620ef3a3-d92c-4241-86bb-511817c9d3cb --non-interactive
      - name: Run EAS build command
        run: npx eas-cli@latest build --platform ios --profile app-review
